# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d2ccb4e4cb7be5fd5a35085421a9c6c5a54dd82bc5d36f5b558b425d6289d4a302ddb512701e90d3030c55e977b5ad6039d161fbfe3146e32ef4e7dd6c6c1ab

test:
  secret_key_base: f7d6735ac171f28a43a51c0a3015efb65317811115be471376438e63cd2f3732936cb1ee9116800c0226c41505c45d835130a11667fc8947b4d0f84bfda51981

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
